### ISSUE TITLE
Random instance name issue

### ISSUE THREAD

**Issue by Avtandilko** [dmitriy-kharchenko/otusplatform-kubespray#2]
Название ноды в GCP должно соответствовать паттерну:
`(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)`

При использовании random возможна генерация невалидного имени, например `5rj3m-worker-instance-0`

Пример ошибки:
```
Error: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.name': '5rj3m-worker-instance-0'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid

  on main.tf line 40, in resource "google_compute_instance" "worker_instance":
  40: resource "google_compute_instance" "worker_instance" {
```

Точно ли нужен random в префиксе названий нод?

**Comment by dmitriy-kharchenko** [comment]
Да, random нужен нам, чтобы можно было параллельно в одном проекте кластера создавать.
